// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohgicmxmirnsplsfwixi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9oZ2ljbXhtaXJuc3Bsc2Z3aXhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwOTk2MDUsImV4cCI6MjA3MDY3NTYwNX0.Wype_qR-c7KtLwzrxbybOfgz2KRM1qnE7mq_cNDtD2M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});